controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_catch_all:
    path: /{url}
    defaults: { _controller: App\Controller\DefaultController::notFound }
    requirements:
        url: .*